<?php
/**
 * Ciudades de peru
 */
global $places;
$places['PE'] = array(
	'AMA' => array(
        "Chachapoyas",
        "Bagua",
        "Bongará",
        "Condorcanqui",
        "Luya",
        "Rodríguez de Mendoza",
        "Utcubamba"
		),
	'ANC' => array(
        "Aija",
        "Antonio Raymondi",
        "Asunción",
        "Bolognesi",
        "Carhuaz",
        "Carlos F. Fitzcarrald",
        "Casma",
        "Corongo",
        "Huaraz",
        "Huari",
        "Huarmey",
        "Huaylas",
        "Mariscal Luzuriaga",
        "Ocros",
        "Pallasca",
        "Pomabamba",
        "Recuay",
        "Santa",
        "Sihuas",
        "Yungay"
		),
	'APU' => array(

        "Abancay",
        "Andahuaylas",
        "Antabamba",
        "Aymaraes",
        "Cotabambas",
        "Chincheros",
        "Grau"
		),
	'ARE' => array(
        "Alto Selva Alegre",
        "Arequipa",
        "Cayma",
        "Cerro Colorado",
        "Characato",
        "Chiguata",
        "Jacobo Hunter",
        "José Luis Bustamante y Rivero",
        "La Joya",
        "Mariano Melgar",
        "Miraflores",
        "Mollebaya",
        "Paucarpata",
        "Pocsi",
        "Polobaya",
        "Quequeña",
        "Sabandía",
        "Sachaca",
        "San Juan de Siguas",
        "San Juan de Tarucani",
        "Santa Isabel de Siguas",
        "Santa Rita de Siguas",
        "Socabaya",
        "Tiabaya",
        "Uchumayo",
        "Vitor",
        "Yanahuara",
        "Yarabamba",
        "Yura"
		),
	'AYA' => array(
        "Huamanga",
        "Cangallo",
        "Huancasancos",
        "Huanta",
        "La Mar",
        "Lucanas	Puquio",
        "Parinacochas",
        "Páucar del Sara Sara",
        "Sucre",
        "Víctor Fajardo",
        "Vilcashuamán"
		),
	'CAJ' => array(
        "Cajamarca",
        "Cajabamba",
        "Celendín",
        "Contumazá",
        "Cutervo",
        "Chota",
        "Hualgayoc",
        "Jaén",
        "Santa Cruz",
        "San Miguel",
        "San Ignacio",
        "San Marcos",
        "San Pablo"
		),
	'CAL' => array(
        "Callao",
        "Bellavista",
        "Carmen de La Legua Reynoso",
        "La Perla",
        "La Punta",
        "Ventanilla",
        "Mi Perú"
		),
	'CUS' => array(
        "Cusco",
        "Acomayo",
        "Anta",
        "Calca",
        "Canas",
        "Canchis",
        "Chumbivilcas",
        "Espinar",
        "La Convención",
        "Paruro	Paruro",
        "Paucartambo",
        "Quispicanchi",
        "Urubamba"
		),
	'HUC' => array(
        "Huánuco",
        "Ambo",
        "Dos de Mayo",
        "Huacaybamba",
        "Huamalíes",
        "Leoncio Prado",
        "Marañón",
        "Pachitea",
        "Puerto Inca",
        "Lauricocha",
        "Yarowilca"
		),
	'HUV' => array(
        "Huancavelica",
        "Acobamba",
        "Angaraes",
        "Castrovirreyna",
        "Churcampa",
        "Huaytará",
        "Tayacaj"
		),
	'ICA' => array(
        "Ica",
        "Chincha",
        "Nazca",
        "Palpa",
        "Pisc"
		),
	'JUN'  => array(
        "Huancayo",
        "Concepción",
        "Chanchamayo",
        "Jauja",
        "Junín",
        "Satipo",
        "Tarma",
        "Yauli",
        "Chupac"
		),
	'LAL' => array(
        "Trujillo",
        "Ascope",
        "Bolívar",
        "Chepén",
        "Julcán",
        "Otuzco",
        "Pacasmayo",
        "Pata",
        "Sánchez Carrión",
        "Santiago de Chuco",
        "Gran Chimú",
        "Vir"
		),
	'LAM' => array(
        "Chiclayo",
        "Ferreñafe",
        "Lambayeque"
		),
	'LIM' => array(
        "Lima",
            "- Ancón",
            "- Ate",
            "- Barranco",
            "- Breña",
            "- Carabayllo",
            "- Chaclacayo",
            "- Chorrillos",
            "- Cieneguilla",
            "- Comas",
            "- El Agustino",
            "- Huaycán4​",
            "- Independencia",
            "- Jesús María",
            "- La Molina",
            "- La Victoria",
            "- Lima",
            "- Lince",
            "- Los Olivos",
            "- Lurigancho",
            "- Lurín",
            "- Magdalena del Mar",
            "- Miraflores",
            "- Pachacamac",
            "- Pucusana",
            "- Pueblo Libre",
            "- Puente Piedra",
            "- Punta Hermosa",
            "- Punta Negra",
            "- Rímac",
            "- San Bartolo",
            "- San Borja",
            "- San Isidro",
            "- San Juan de Lurigancho",
            "- San Juan de Miraflores",
            "- San Luis",
            "- San Martín de Porres",
            "- San Miguel",
            "- Santa Anita",
            "- Santa María de Huachipa",
            "- Santa María del Mar",
            "- Santa Rosa",
            "- Santiago de Surco",
            "- Surquillo",
            "- Villa El Salvador",
            "- Villa María del Triunfo",
        "-",
        "Barranca",
            "- Barranca",
            "- Paramonga",
            "- Pativilca",
            "- Supe",
            "- Supe Puerto",
        "-",
        "Cajatambo",
            "- Manás",
            "- Gorgor",
            "- Huancapón",
            "- Cajatambo",
            "- Copa",
        "-",
        "Canta",
            "- Canta",
            "- Arahuay",
            "- Huamantanga",
            "- Huaros",
            "- Lachaqui",
            "- San Buenaventura",
            "- Santa Rosa de Quives",
        "-",
        "Cañete",
            "- Asia",
            "- Calango	",
            "- Cerro Azul",
            "- Chilca",
            "- Coayllo",
            "- Imperial",
            "- Lunahuaná",
            "- Mala",
            "- Nuevo Imperial",
            "- Pacarán",
            "- Quilmaná",
            "- San Antonio",
            "- San Luis",
            "- San Vicente de Cañete",
            "- Santa Cruz de Flores",
            "- Zúñiga",
        "-",
        "Huaral",
            "- Atavillos Alto",
            "- Atavillos Bajo",
            "- Aucallama",
            "- Chancay",
            "- Huaral",
            "- Ihuarí",
            "- Lampían",
            "- Pacaraos",
            "- Santa Cruz de Andamarca",
            "- Sumbilca",
            "- San Miguel de Acos",
            "- Veintisiete de Noviembre",
        "-",
        "Huarochirí",
            "- Matucana",
            "- Antioquía",
            "- Callahuanca",
            "- Carampoma",
            "- Chicla",
            "- Cuenca",
            "- Huachupampa",
            "- Huanza",
            "- Huarochirí",
            "- Lahuaytambo",
            "- Langa",
            "- Laraos (San Pedro de Laraos)",
            "- Mariatana",
            "- Ricardo Palma",
            "- San Andrés de Tupicocha",
            "- San Antonio (de Chaclla)",
            "- San Bartolomé",
            "- San Damián",
            "- San Juan de Iris",
            "- San Juan de Tantaranche",
            "- San Lorenzo de Quinti",
            "- San Mateo",
            "- San Mateo de Otao",
            "- San Pedro de Casta",
            "- San Pedro de Huancayre",
            "- Sangallaya",
            "- Santa Cruz de Cocachacra",
            "- Santa Eulalia",
            "- Santiago de Anchucaya",
            "- Santiago de Tuna",
            "- Santo Domingo de los Olleros",
            "- San Jerónimo de Surco",
        "-",
        "Huaura",
            "- Ámbar",
            "- Caleta de Carquín",
            "- Checras",
            "- Huacho",
            "- Hualmay",
            "- Huaura",
            "- Leoncio Prado",
            "- Paccho",
            "- Santa Leonor",
            "- Santa María",
            "- Sayán",
            "- Végueta",
        "-",
        "Oyón",
            "- Oyón",
            "- Andajes",
            "- Caujul",
            "- Cochamarca",
            "- Naván",
            "- Pachangara",
        "-",
        "Yauyos",
            "- Yauyos",
            "- Alis",
            "- Ayauca3​",
            "- Ayavirí",
            "- Azángaro",
            "- Cacra",
            "- Carania",
            "- Catahuasi",
            "- Chocos",
            "- Cochas",
            "- Colonia",
            "- Hongos",
            "- Huampará",
            "- Huancaya",
            "- Huangáscar",
            "- Huantán",
            "- Huáñec",
            "- Laraos",
            "- Lincha",
            "- Madeán",
            "- Miraflores",
            "- Omas",
            "- Putinza",
            "- Quinches",
            "- Quinocay",
            "- San Joaquín",
            "- San Pedro de Pilas",
            "- Tanta",
            "- Tauripampa",
            "- Tomas",
            "- Tupe",
            "- Víñac",
            "- Vitis"
		),
	'LMA' => array(
        'Municipalidad Metropolitana de Lima',
		),
	'LOR' => array(
        "Maynas",
        "Alto Amazonas",
        "Loreto",
        "Mariscal Ramón Castilla",
        "Requena",
        "Ucayali",
        "Datem del Marañón",
        "Putumay"
		),
	'MDD' => array(
        "Tambopata",
        "Manu",
        "Tahuamanu"
		),
	'MOQ' => array(
        "Mariscal Nieto",
        "General Sánchez Cerro",
        "Ilo"
		),
	'PAS' => array(
        "Pasco",
        "Daniel A. Carrión",
        "Oxapampa"
		),
	'PIU' => array(
        "Piura",
        "Ayabaca",
        "Huancabamba",
        "Morropón",
        "Paita",
        "Sullana",
        "Talara",
        "Sechur"
		),
	'PUN' => array(
        "Puno",
        "San Román",
        "Azángaro",
        "Chucuito",
        "El Collao",
        "Melgar",
        "Carabaya",
        "Huancané",
        "Sandia",
        "San Antonio de Putina",
        "Lampa",
        "Yunguyo",
        "Moh"
		),
	'SAM' => array(
        "Moyobamba",
        "Bellavista",
        "El Dorado",
        "Huallaga",
        "Lamas",
        "Mariscal Cáceres",
        "Picota",
        "Rioja",
        "San Martín",
        "Tocache"
		),
	'TAC' => array(
        "Candarave",
        "Jorge Basadre",
        "Tacna",
        "Tarata"
		),
	'TUM' => array(
        "Tumbes",
        "Zarumilla",
        "Contralmirante Villar"
		),
	'UCA' => array(
        "Coronel Portillo",
        "Atalaya",
        "Padre Abad",
        "Purús"
		)
	);